# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfb9906faa49bb20191c1e88ff76c6da3feb8dde83dcb9ebd0a8316ffcf9c4abf106151829c7103f59f9ecfad45d193c6178185e416aaeb4e05f263b6b19f225

test:
  secret_key_base: 7fca68c243c78fa6d8bf52d82515757d04a62cfd145588ad63afbe5b4c9a14dca1db31a83aeb366c9d8f39d8abdbe1b31b6937b1e728a3e21796adaf1b069f98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
